# Generated by Django 3.2.18 on 2023-03-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tink',
            new_name='link',
        ),
    ]
